### PR TITLE
Connector not mapping user field with new entry

### PR DESCRIPTION
**Pull request by Idealien**
See #5583 for test case data and scenario.

### CODE REVIEW

**Comment by richardW8k** [comment]
This works but I think there will be times when people want to use the `gravityflowformconnector_{type}__use_choice_text` filter to return the choice text when mapped to other field types.

Perhaps the best place to resolve this would be in `Gravity_Flow_Field_User::get_value_export` so it only returns the display name when when `$use_text` or `$is_csv` is `true`. We should probably make the same change in `Gravity_Flow_Field_Assignee_Select`, `Gravity_Flow_Field_Role`, and `Gravity_Flow_Field_Multi_User`.

@stevehenty what do you think?

**Comment by stevehenty** [comment]
Yeah, I agree. That should also make `{all_fields:value}` work consistently.

**Comment by Idealien** [comment]
Thx. Will leave this PR/branch open (for now) but continue discussion under https://github.com/gravityflow/gravityflow/tree/5583-value-exports once it is ready for PR. The initial commit there has successful test support for addressing the issues of 5583 for Gravity_Flow_Field_User and the portion of Gravity_Flow_Field_Assignee_Select related to user_id. Mappings for role and multi-user need additional testing still.

**Comment by Idealien** [comment]
Closing in favour of https://github.com/gravityflow/gravityflow/pull/148

**Pull request closed without merging**
